### PR TITLE
Sign up through a conversion box below a blog article [#132900271]

### PR DESCRIPTION
**Pull request by kdamball**
### Testing:
- Try signing up through the form at the bottom of the page
- It should autofill the signup form on the sign-up page 

Keep in mind: It might not auto-fill the first name if this is not pushed to production: https://github.com/honeypotio/honeypot/pull/547

### CODE REVIEW

**Comment by kdamball** [comment]
@andreruffert do you mind having a look? 😃

**Comment by Batjohe** [comment]
Yo, some comments:
-Less space between author and the box, same as above. Because I guess we're not adding the social media yet? 
screen shot 2016-11-15 at 15 15 30
- Would also make the headline bolder. 
- I would reduce a bit of space between headline and the text (might get better with just making the headline bold) 
screen shot 2016-11-15 at 15 18 41
- Name doesn't follow to the signup box only email
screen shot 2016-11-15 at 15 14 07

**Comment by kdamball** [comment]
> Name doesn't follow to the signup box only email 

- It will have to wait until honeypotio/honeypot#547 is deployed 🙂

**Comment by andreruffert** [comment]
@kdamball LGTM!

**Pull request merged**
