### PR TITLE
chore: add lossless image compression

### PR DESCRIPTION
**Pull request by andreruffert**
- Relocate `authors` + `cover-images` to `assets`
- Introduce a gulp task for lossless image compression

screen shot 2016-10-25 at 12 10 51
_In total we save 17MB_
- [x] https://www.pivotaltracker.com/n/projects/1474304/stories/119715503

### CODE REVIEW

**Comment by duksis** [comment]
@andreruffert I see a lot of images changed but don't see the gulp task

**Comment by andreruffert** [comment]
@duksis GitHub does not display the entire diff. You can take a look at the [gulpfile.js](https://github.com/honeypotio/blog-honeypot-io/blob/chore/add-lossless-image-compression-119715503/gulpfile.js) directly in the [branch](https://github.com/honeypotio/blog-honeypot-io/tree/chore/add-lossless-image-compression-119715503).

**Comment by duksis** [comment]
would suggest to commit code in a separate commit - in this case the rake task one commit the usage of it - transforming the images as another

**Comment by andreruffert** [comment]
The problem I see with separate commits is that the gulp task will not work without relocating the images. I would commit code which is not working...

**Comment by duksis** [comment]
the problem I see now is that you commit code that I can't see ;)

if you had committed the gulp task and moving of 1 image it would work and I would be able to see the code by clicking on the commit right?

**Pull request merged**
